# Generated by Django 4.2.9 on 2024-01-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('factory', 'Завод'), ('RetailNetwork', 'Розничная сеть'), ('IndividualEntrepreneur', 'ИП')], default='factory', verbose_name='Тип звена')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=10)),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, max_digits=13)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='ElectronicsNetwork.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_suppliers', to='ElectronicsNetwork.supplier')),
            ],
        ),
    ]
