# Generated by Django 4.2.9 on 2024-01-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicsNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'поставщик', 'verbose_name_plural': 'поставщики'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='debt_to_supplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Задолженность перед поставщиком'),
        ),
    ]
